[server]
# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) we are running in the Streamlit Atom plugin.
headless = true

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = false

[runner]
# Raise an exception after adding unserializable data to Session State. Some execution environments may require serializing all data in Session State, so it may be useful to detect incompatibility during development, or when the execution environment will stop supporting it in the future.
# Default: false
#enforceSerializableSessionState = false

[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = 'dark'

# Primary accent color for interactive elements.
primaryColor = '#BD93F9'

# Background color for the main content area.
backgroundColor = '#282A36'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#44475A'

# Color used for almost all text.
textColor = '#F8F8F2'
