[server]
# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) we are running in the Streamlit Atom plugin.
headless = true

[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = 'dark'

# Primary accent color for interactive elements.
primaryColor = '#BD93F9'

# Background color for the main content area.
backgroundColor = '#282A36'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#44475A'

# Color used for almost all text.
textColor = '#F8F8F2'
