page_title = 'Trailling Stop Binance'

[binance]
api_key = 'orxThbVS0OyqnMZ1shu51RxPYXWS1HCA5lxc8mDQ6AH1MOHHslpBjgYXSflxnDJX'
api_secret = '8YBdmg31G7Wcv8GOuyAykXSPrUzhq7XCDGTOUHc4rjEm8kJhVTmKf4XqbOb5wUtP'